### ISSUE TITLE
generation is failing

### ISSUE THREAD

**Issue by jadekler** [googleapis/gapic-generator-go#228] opened 2019-10-09 19:28 UTC
```
+ cp -r artman-genfiles/gapi-cloud-spanner-go/cloud.google.com/go/spanner /var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/tmp.RN9SSkbV/gocloud
+ rm -rf /tmp/cloud.google.com
+ read -r
+ IFS=,
+ read -r input mod retrycfg apicfg release
+ microgen google/cloud/texttospeech/v1 ' --go-gapic-package cloud.google.com/go/texttospeech/apiv1;texttospeech' ' --grpc-service-config google/cloud/texttospeech/v1/texttospeech_grpc_service_config.json' ' --gapic-service-config google/cloud/texttospeech/v1/texttospeech_v1.yaml' ' --release-level alpha'
+ input=google/cloud/texttospeech/v1
+ options=' --go-gapic-package cloud.google.com/go/texttospeech/apiv1;texttospeech  --grpc-service-config google/cloud/texttospeech/v1/texttospeech_grpc_service_config.json  --gapic-service-config google/cloud/texttospeech/v1/texttospeech_v1.yaml  --release-level alpha'
+ docker run --user 525522 --mount type=bind,source=/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/tmp.RN9SSkbV/googleapis,destination=/conf,readonly --mount type=bind,source=/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/tmp.RN9SSkbV/googleapis/google/cloud/texttospeech/v1,destination=/in/google/cloud/texttospeech/v1,readonly --mount type=bind,source=/tmp,destination=/out --rm gcr.io/gapic-images/gapic-generator-go:0.8.1 --go-gapic-package 'cloud.google.com/go/texttospeech/apiv1;texttospeech' --grpc-service-config google/cloud/texttospeech/v1/texttospeech_grpc_service_config.json --gapic-service-config google/cloud/texttospeech/v1/texttospeech_v1.yaml --release-level alpha
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/tmp.RN9SSkbV/googleapis.
See 'docker run --help'.
```

**Comment by noahdietz** [comment] 2019-10-09 19:48
It looks like you are running this from a temporary directory containing `googleapis`? 

The path used in the binding is `$PWD` meaning that it's expected that this script is invoked from the `googleapis` repo directory.

I can't reproduce this from a `/tmp/googleapis` directory. Furthermore, this has worked previously as there is a microgen GAPIC published in google-cloud-go.

I need more info on the invocation environment but my guess is it's environment related.

**Comment by noahdietz** [comment] 2019-10-09 20:04
I can repro with our internal docs on regeneration. Looks like it might be [this issue](https://stackoverflow.com/questions/45122459/docker-mounts-denied-the-paths-are-not-shared-from-os-x-and-are-not-known/45123074).

**Comment by noahdietz** [comment] 2019-10-09 21:04
Fixed by https://code-review.googlesource.com/c/gocloud/+/46673

**Closed by noahdietz** 2019-10-09 21:04 UTC
Labels: priority: p1, type: bug
