### ISSUE TITLE
replace github.com/golang/protobuf with google.golang.org/protobuf

### ISSUE THREAD

**Issue by julieqiu** [googleapis/gapic-generator-go#1414] opened 2023-10-05 22:11 UTC
The github.com/golang/protobuf module has been deprecated as of September 2021. The recommendation is to migrate to google.golang.org/protobuf instead.

**Comment by noahdietz** [comment] 2023-10-05 22:15
Duplicate of https://github.com/googleapis/gapic-generator-go/issues/348

thanks though!

**Closed by noahdietz** 2023-10-05 22:15 UTC
Labels: priority: p2, type: cleanup
